[WIP] Retrieve messages guide
Elixir-Girls/elixirgirls.github.io pull request #45
Opened 2017-09-14 12:17 UTC by daphsta

2017-09-14 23:27 UTC, brentonannan requested changes
Produced `html` files are named after these files, so well-named files would be useful for SEO etc.

Also, these should be `.html.erb` files.

... I just looked further - seems you have a mix of files in here, not sure what's what. Also, the `persistence` guide seems to be re-added under `source`.

2017-09-14 23:27 UTC, brentonannan commented on source/guide1.html
> +<%= partial "partials/guides-nav" %>
If you rebase onto master, and put this into `source/guides/`, you don't need wrapping stuff, it's in a layout.

2017-09-14 23:27 UTC, brentonannan commented on source/guide1.html
> +<!-- jQuery -->
Also in a partial.

2017-09-14 23:27 UTC, brentonannan commented on source/guide1.html
> +          <% code("elixir") do %>
I *so* wish I'd known about this helper sooner.

2017-09-14 23:49 UTC, daphsta commented
@brentonannan opps, my bad for committing an incomplete file. That's all fixed now

2017-09-15 04:05 UTC, daphsta commented
@catherine-jones @brentonannan is this good to go?

2017-09-15 10:03 UTC, brentonannan commented
Hey, sorry @daphsta, I had a hella crazy day today and didn't get a chance to review :disappointed:.

2017-09-15 22:49 UTC, daphsta commented
No worries @brentonannan, totally understand that :)
On Fri, Sep 15, 2017 at 8:03 PM Brenton Annan <notifications@github.com>
wrote:

> Hey, sorry @daphsta <https://github.com/daphsta>, I had a hella crazy day
> today and didn't get a chance to review 😞.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/Elixir-Girls/elixir-girls.github.io/pull/45#issuecomment-329739442>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACOmC2IiLKW10hXw_55o-Q-SvhpcnFJAks5sikt_gaJpZM4PXfR->
> .
>

2018-10-20 07:13 UTC, merged